# Generated by Django 5.2.6 on 2025-09-22 20:30

from django.db import migrations


def create_initial_services(apps, schema_editor):
    # This migration is deprecated and replaced by 0015_update_service_prices_and_structure
    # Keeping this as a no-op to maintain migration history
    pass


def remove_initial_services(apps, schema_editor):
    # This migration is deprecated and replaced by 0015_update_service_prices_and_structure
    # Keeping this as a no-op to maintain migration history
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_services, remove_initial_services),
    ]
