# Generated by Django 5.2.6 on 2025-09-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_details_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=200, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('deposit_amount', models.IntegerField(default=2500)),
                ('total_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deposit_captured', 'Deposit Captured'), ('fully_captured', 'Fully Captured'), ('deposit_refunded', 'Deposit Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_captured_at', models.DateTimeField(blank=True, null=True)),
                ('fully_captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='main.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
