# Generated by Django 5.2.6 on 2025-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('regular', 'Regular Car'), ('suv', 'SUV/Large Vehicle')], default='regular', max_length=20),
        ),
    ]
