# Generated by Django 5.2.6 on 2025-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vehicle_type',
            field=models.CharField(choices=[('regular', 'Regular Car'), ('suv', 'SUV/Large Vehicle')], default='regular', max_length=20),
        ),
    ]
