# Generated by Django 5.2.6 on 2025-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_convert_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='saved_payment_method_id',
            field=models.CharField(blank=True, help_text='Saved payment method for future charges', max_length=200, null=True),
        ),
    ]
