# Generated by Django 5.2.6 on 2025-10-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_saved_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deposit_amount',
            field=models.IntegerField(default=2500, help_text='Deposit amount in cents (e.g., 2500 = $25.00)'),
        ),
    ]
